version: "3.7"

services:
  queue:
    image: schickling/beanstalkd
    entrypoint: /usr/bin/beanstalkd
    ports:
      - 11300:11300
    volumes:
      - ./queuedata/beanstalkd:/queuedata

  producer:
    depends_on:
      - queue
    build:
      context: .
    command: python producer.py beanstalkd --queue-host=queue --queue-port=11300 -n=1000
    volumes:
      - .:/app

  consumer:
    depends_on:
      - queue
    build:
      context: .
    command: python consumer.py beanstalkd --queue-host=queue --queue-port=11300 -n=1000
    volumes:
      - .:/app
