version: "3.7"

services:
  queue:
    image: redis
    command: redis-server --save '' --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./queuedata/redis-aof:/data

  producer:
    depends_on:
      - queue
    build:
      context: .
    command: python producer.py redis --queue-host=queue --queue-port=6379 -n=1000
    volumes:
      - .:/app

  consumer:
    depends_on:
      - queue
    build:
      context: .
    command: rq worker --url=redis://queue:6379 --worker-class=rq.worker.SimpleWorker --max-idle-time=5 --results-ttl=0
    volumes:
      - .:/app
